run:
  deadline: 10m
  skip-files: [ ]
  skip-dirs:
    - pkg/crd/generated

linters-settings:
  govet:
    enable-all: true
    disable:
      - fieldalignment
  gocyclo:
    min-complexity: 15
  maligned:
    suggest-new: true
  goconst:
    min-len: 5
    min-occurrences: 3
  misspell:
    locale: US
  funlen:
    lines: -1
    statements: 50
  godox:
    keywords:
      - FIXME
  gofumpt:
    extra-rules: true
  depguard:
    list-type: blacklist
    include-go-root: false
    packages:
      - github.com/sirupsen/logrus
      - github.com/pkg/errors
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - sloppyReassign
      - rangeValCopy
      - octalLiteral
      - paramTypeCombine # already handle by gofumpt.extra-rules
      - unnamedResult
    settings:
      hugeParam:
        sizeThreshold: 110
  gomoddirectives:
    replace-allow-list:
      - github.com/abbot/go-http-auth
  goheader:
    values:
      const:
        COMPANY: Traefik Labs
    template: |-
      Copyright (C) {{ YEAR }} {{ COMPANY }}

      This program is free software: you can redistribute it and/or modify
      it under the terms of the GNU Affero General Public License as published
      by the Free Software Foundation, either version 3 of the License, or
      (at your option) any later version.

      This program is distributed in the hope that it will be useful,
      but WITHOUT ANY WARRANTY; without even the implied warranty of
      MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
      GNU Affero General Public License for more details.

      You should have received a copy of the GNU Affero General Public License
      along with this program. If not, see <https://www.gnu.org/licenses/>.

  importas:
    no-unaliased: true
    alias:
    # Standard Kubernetes rewrites:
    - alias: corev1
      pkg: "k8s.io/api/core/v1"
    - alias: netv1
      pkg: "k8s.io/api/networking/v1"
    - alias: netv1beta1
      pkg: "k8s.io/api/networking/v1beta1"
    - alias: admv1
      pkg: "k8s.io/api/admission/v1"
    - alias: admv1beta1
      pkg: "k8s.io/api/admission/v1beta1"
    - alias: extv1beta1
      pkg: "k8s.io/api/extensions/v1beta1"
    - alias: metav1
      pkg: "k8s.io/apimachinery/pkg/apis/meta/v1"
    - alias: ktypes
      pkg: "k8s.io/apimachinery/pkg/types"
    - alias: kerror
      pkg: "k8s.io/apimachinery/pkg/api/errors"
    - alias: clientset
      pkg: "k8s.io/client-go/kubernetes"
    - alias: kubemock
      pkg: "k8s.io/client-go/kubernetes/fake"

    # Traefik Kubernetes rewrites:
    - alias: traefikv1alpha1
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/api/traefik/v1alpha1"
    - alias: traefikclientset
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/generated/client/traefik/clientset/versioned"
    - alias: traefikinformer
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/generated/client/traefik/informers/externalversions"
    - alias: traefikkubemock
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/generated/client/traefik/clientset/versioned/fake"

    # Hub Kubernetes rewrites:
    - alias: hubv1alpha1
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/api/hub/v1alpha1"
    - alias: hubclientset
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/generated/client/hub/clientset/versioned"
    - alias: hubinformer
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/generated/client/hub/informers/externalversions"
    - alias: hubkubemock
      pkg: "github.com/traefik/hub-agent-kubernetes/pkg/crd/generated/client/hub/clientset/versioned/fake"

    # Misc:
    - alias: jwtreq
      pkg: "github.com/golang-jwt/jwt/v4/request"

linters:
  enable-all: true
  disable:
    - maligned # deprecated
    - interfacer # deprecated
    - scopelint # deprecated
    - golint # deprecated
    - sqlclosecheck # not relevant (SQL)
    - rowserrcheck # not relevant (SQL)
    - execinquery # not relevant (SQL)
    - cyclop # duplicate of gocyclo
    - lll
    - dupl
    - wsl
    - nlreturn
    - gomnd
    - goerr113
    - wrapcheck
    - exhaustive
    - exhaustivestruct
    - exhaustruct
    - nonamedreturns
    - testpackage
    - tparallel
    - paralleltest
    - prealloc
    - forcetypeassert
    - bodyclose # Too many false positives: https://github.com/timakin/bodyclose/issues/30
    - ifshort # disable due to false-positive, the linter will be fixed https://github.com/esimonov/ifshort
    - varnamelen
    - nilnil
    - ireturn
    - contextcheck
    - errchkjson

issues:
  exclude-use-default: false
  max-per-linter: 0
  max-same-issues: 0
  exclude:
    - 'ST1000: at least one file in a package should have a package comment'
    - 'G204: Subprocess launched with variable'
    - 'G304: Potential file inclusion via variable'
  exclude-rules:
    - path: .*_test.go
      linters:
        - funlen
        - noctx
        - gochecknoinits
        - gochecknoglobals
        - maintidx
        - nosnakecase
    - path: pkg/crd/api/.*
      linters:
        - tagliatelle
    - path: pkg/crd/api/.*/v1alpha1/register.go
      linters:
        - gochecknoglobals
    - path: pkg/acp/admission/reviewer/reviewer.go
      linters:
        - goconst
    - path: pkg/topology/state/fetcher.go
      text: "Function 'watchAll' has too many statements"
      linters:
        - funlen
    - path: pkg/topology/state/fetcher.go
      text: "cyclomatic complexity 19 of func `watchAll` is high"
      linters:
        - gocyclo
    - path: pkg/metrics/protocol/protocol.go
      text: '[[:alpha:]]+V\dSchema is a global variable'
    # False positive.
    - path: pkg/metrics/store_test.go
      text: 'Multiplication of durations: `-1 \* time\.Duration\(n\) \* gran`'
    # Keep for historical reason.
    - path: pkg/topology/state/cluster.go
      text: "json\\(camel\\): got '(metricsURLs)' want '(metricsUrLs)'"
    # Reducing cyclomatic complexity would reduce readability.
    - path: pkg/acp/admission/reviewer/traefik_ingress_route.go
      linters:
        - gocyclo
    - path: pkg/acp/admission/reviewer/traefik_ingress.go
      linters:
        - gocyclo
    - path: pkg/version/version.go
      linters:
        - gochecknoglobals
    # Harmful to code readability.
    - path: pkg/acp/admission/webhook.go
      linters:
        - errname
    - path: pkg/crd/api/hub/v1alpha1/access_control_policy.go
      linters:
        - gosec # sha1 is not used to encrypt data, no security issue
    - path: pkg/acp/watcher.go
      linters:
        - gocognit
    - path: pkg/crd/api/hub/v1alpha1/edge_ingress.go
      linters:
        - gosec # sha1 is not used to encrypt data, no security issue
    - text: "O_WRONLY|O_RDWR|O_CREATE|O_TRUNC|O_APPEND"
      linters:
        - nosnakecase
    - path: pkg/acp/oidc/oidc.go
      text: "Function 'ServeHTTP' has too many statements"
      linters:
        - funlen
    # Reducing cyclomatic complexity would reduce readability.
    - path: pkg/acp/oidc/oidc.go
      text: "cyclomatic complexity 20 of func `(.*).ServeHTTP` is high"
      linters:
        - gocyclo
    - path: pkg/acp/oidc/http.go
      linters:
        - gosec
    - path: pkg/acp/oidc/oidc_test.go
      linters:
        - gosec
